- name: nginx install
  hosts: frontend
  tasks:
  - name: install nginx
    ansible.builtin.package:
      name: nginx
      state: present
      msg: "installing nginx"

  - name: starting the service
    ansible.builtin.package:
      name: nginx
      state: started
      enabled: yes
