- name: nginx install
  hosts: frontend
  become: yes
  tasks:
  - name: install nginx
    ansible.builtin.package:
      name: nginx
      state: present


  - name: starting the service
    ansible.builtin.package:
      name: nginx
      state: started
      enabled: yes
